site_name: nerd.dad
site_description: a blog for all nerd dads
site_url: https://nerd.dad/
copyright: Copyright &copy; 2024 - 2050 nerd.dad
repo_url: https://github.com/nerddotdad/nerd.dad
repo_name: nerddotdad/nerd.dad
edit_uri: edit/main/docs/

## Nav is placeholder for now
# nav:
#   - Section:
#     - section/index.md 
#     - Page n: section/page-n.md

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.action.edit
    - content.action.view

watch:
  - overrides

plugins:
  - search
  - blog
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: nerddotdad/nerd.dad
      branch: main

extra:
  version:
    provider: mike
    alias: true
  social:
  - icon: fontawesome/brands/discord
    link: https://discordapp.com/users/64831697186721792
    name: My Discord
  - icon: fontawesome/brands/github
    link: https://github.com/nerddotdad
    name: nerd.dad github
  - icon: fontawesome/solid/cubes
    link: https://github.com/nerddotdad/truecharts
    name: nerd.dad cluster
  generator: false

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg